// app/layout.tsx
import '@/app/globals.css'

export const metadata = {
  title: 'My App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>       
        <main className="container mx-auto p-4">
          {children}
        </main>
      </body>
    </html>
  )
}
